version: 2.1

jobs:
  test-ios16_4-iPhone_14_Pro:
    macos:
      xcode: 14.3.1
    steps:
      - checkout
      - run: xcodebuild clean test -scheme FloatingPanel -workspace FloatingPanel.xcworkspace -destination 'platform=iOS Simulator,OS=16.4,name=iPhone 14 Pro'
  test-ios15_5-iPhone_13_Pro:
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - run: xcodebuild clean test -scheme FloatingPanel -workspace FloatingPanel.xcworkspace -destination 'platform=iOS Simulator,OS=15.5,name=iPhone 13 Pro'
  test-ios14_5-iPhone_12_Pro:
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - run: xcodebuild clean test -scheme FloatingPanel -workspace FloatingPanel.xcworkspace -destination 'platform=iOS Simulator,OS=14.5,name=iPhone 12 Pro'
  test-ios13_7-iPhone_11_Pro:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run: xcodebuild clean test -scheme FloatingPanel -workspace FloatingPanel.xcworkspace -destination 'platform=iOS Simulator,OS=13.7,name=iPhone 11 Pro'

workflows:
  test: 
    jobs:
      - test-ios16_4-iPhone_14_Pro
      - test-ios15_5-iPhone_13_Pro
      - test-ios14_5-iPhone_12_Pro
      - test-ios13_7-iPhone_11_Pro
